spring:
  application:
    name: audio
  datasource:
        name: audio
        url: jdbc:mysql://localhost:3306/practice?characterEncoding=utf-8&useSSL=true
        username: root
        password: mysql
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      force: true
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  thymeleaf:
    prefix: classpath:/static/
    
mybatis: 
  mapper-locations: classpath:/mapper/*.xml
  
springbootdo:
  uploadPath: D:/var/uploaded_files/

server: 
  max-http-header-size: 100000
  port: 9999
  servlet:
    context-path: /audio